{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ambassador-auth-jwt.fullname" . }}
  labels:
    app: {{ template "ambassador-auth-jwt.name" . }}
    chart: {{ template "ambassador-auth-jwt.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  annotations:
    getambassador.io/config: |
        ---
        apiVersion: ambassador/v1
        kind: AuthService
        name: authentication
        auth_service: {{ template "ambassador-auth-jwt.fullname" . }}
        {{- range $key, $value := .Values.service.config }}
        {{ $key }}: {{ $value }}
        {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: {{ template "ambassador-auth-jwt.name" . }}
    release: {{ .Release.Name }}
    {{- if or .Values.blueGreen }}
    bluegreen: {{ required "activeBlueGreen required when using blue/green labels" .Values.activeBlueGreen }}
    {{- end }}
{{- end }}
